services:
  - type: web
    name: ai-toy-server
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: UDP_HOST
        value: 0.0.0.0
      - key: UDP_PORT
        value: 5005
      - key: HTTP_HOST
        value: 0.0.0.0
      - key: HTTP_PORT
        value: 5006
      - key: MQTT_BROKER
        value: broker.emqx.io
      - key: MQTT_PORT
        value: 1883
